/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package newrelic.agent.troubleshooting

import spock.lang.Specification

class AppSpec extends Specification {
    def "application has a constructor"() {
        expect:
        new App() != null
    }
}
