/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package newrelic.agent.troubleshooting;

import com.newrelic.api.agent.Trace;
import newrelic.agent.troubleshooting.transactions.Transaction;
import newrelic.agent.troubleshooting.transactions.Transaction0;

public class App {
    public static void main(String[] args) {

        while (true) {
            Transaction transaction = new Transaction0();
            transaction.startTransaction();
            try {
                Thread.sleep(3000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    @Trace(dispatcher = true)
    private static void createTransaction() {
        System.out.println("a transaction has been created!");
    }
}
